### ISSUE TITLE
Debugging commands

### ISSUE THREAD

**Issue by fleimgruber** [ahrm/sioyek-python-extensions#15]
I am trying https://github.com/ahrm/sioyek-python-extensions#-import_annotations after setting the `python` in `prefs_user.config`:

```
python "C:\Users\user\project\.venv\Scripts\python.exe"
```

as mentioned in https://github.com/ahrm/sioyek-python-extensions/issues/1#issuecomment-1403921159. Now how can I debug this? Running the command `: _import_annotations` does not seem to have any effect. I can import the sioyek library from CLI alright:

```
.\.venv\Scripts\python.exe -c "import sioyek.import_annotations"
```

**Comment by ahrm** [comment]
You can run the python command manually from the command line:
```
python -m sioyek.import_annotations "%{sioyek_path}" "%{local_database}" "%{shared_database}" "%{file_path}"

```

(after replacing the %{} variables with the correct values), and see if it works.

**Comment by fleimgruber** [comment]
@ahrm thanks for checking back. I saw changes in the PDF opened in sioyek after running the command.

An observation: It's a two-column paper and the highlight annotation is colored a bright yellow as expected - the contents of the left column up until the highlight annotation are colored in a lighter yellow though which disappears if the highlight annotation is not visible any more, i.e. scrolling it out of the visible range. If this is not a known issue, I will create a separate one and try to reproduce with a minimal PDF.

To the issue at hand: How can I search for annotation contents to check whether the import was successful?

**Comment by ahrm** [comment]
> How can I search for annotation contents to check whether the import was successful?

You can see a list of highlights by pressing `gh`.

**Comment by fleimgruber** [comment]
Ok, it seems to work from CLI, but not with `_import_annotations` from inside sioyek. How to debug `_import_annotations` further?

Also, only the highlighted text is shown, not the annotation contents (this is what SumatraPDF calls the text that can be associated with a highlight). Do you have an annotated PDF that you could share with which I can test this more?

**Comment by fleimgruber** [comment]
For reference, I currently run with this prefs_user.config:

```
python "C:\Users\user\project\.venv\Scripts\python.exe"

new_command _import_annotations python -m sioyek.import_annotations "%{sioyek_path}" "%{local_database}" "%{shared_database}" "%{file_path}"
```

**Comment by ahrm** [comment]
> Also, only the highlighted text is shown, not the annotation contents (this is what SumatraPDF calls the text that can be associated with a highlight)

We don't have that in sioyek.

**Comment by fleimgruber** [comment]
Regarding the observation in https://github.com/ahrm/sioyek-python-extensions/issues/15#issuecomment-1584453023, I could not reproduce the behavior in a two-column article compiled locally with LaTeX, so I suspect the issue is with the PDF with which I tested.

**Comment by ahrm** [comment]
> Do you mean that we don't have that yet or that you don't plan on working on it?

Currently, I don't have any plans to add this feature, this may change in the future though. For now, you could add a bookmark in the same location as the highlight if you want to add some text information.
