### ISSUE TITLE
Extract_highlights. No selection and portal in new document.

### ISSUE THREAD

**Issue by Floyr** [ahrm/sioyek-python-extensions#18]
Hello, dear developers!

If possible, please help me with one question. In the PFD tutorial document, I am making 6 notes using the "hy" command. Then I run the command "-extract_highlights". A new file is created, but it has no highlights, and there are no "portals" in it (the new file has only sections of the highlights that were made in the original file). 

If I understood correctly, in the video in the instructions, when you scroll through the created file with notes, where a fragment will be highlighted and there will be a transition to the place where this note was made in the original file.

Please advise me if this can be fixed in any way, with respect, Floyr.

![ER_STR_20_OTY](https://github.com/ahrm/sioyek-python-extensions/assets/122818180/de4603b4-0094-4148-b068-c87b752ab10c)

**Comment by ahrm** [comment]
Portals are shown in the highlight document's helper window. You can open it by pressing f12 (or executing toggle_window_configuration).

**Comment by Floyr** [comment]
Ooops, I missed a point, thanks!
I'll write it down in case anyone needs it.
After executing the command, you will need to press the "F12" button in the new file, and then everything will work as in the example in the video.
