### ISSUE TITLE
extension not working when running the sioyek app from dock

### ISSUE THREAD

**Issue by jinjiaodawang** [ahrm/sioyek-python-extensions#19]
### Description
I am experiencing an issue with shared memory when running the sioyek app from dock. The problem seems to be specific to the way the app is launched. Below are the details of my system and a description of the problem:
### System Information:
- **OS**: macOS 14.0
- **Platform**: ARM64 (M2)
- **Application Version**: sioyek 2.0.0,  sioyek-python 0.31.11

Issue Description:

1.  When the sioyek app is run directly from Dock, all extension commands have no response.
2.  If I launch sioyek and then run a separate terminal:
```
./sioyek --execute-command "python3 -m sioyek.translate /Applications/sioyek.app/Contents/MacOS/ ' proxies configuration files'"
```
 I receive the following message:
```
tutorial_path: /Applications/sioyek.app/Contents/MacOS/tutorial.pdf
last_opened_file_address_path: /Users/lee/Library/Application Support/sioyek/last_document_path.txt
shader_path: /Applications/sioyek.app/Contents/MacOS/shaders
Creating shared memory block...
Shared memory already exists: this is a secondary application.
Secondary application attaching to shared memory block...
Secondary application successfully attached to shared memory block.
Secondary application sent message to IPC server.
```
  It appears that shared memory is not working as expected in this scenario.
3. If I launch sioyek and then run a separate terminal:
```
python3 -m sioyek.translate xxx ' proxies configuration'
```
Translated words appeared in sioyek status bar successfully.
4. If I run sioyek directly from the terminal, all commands run normally without any issue.
It seems like there may be an issue related to shared memory when running sioyek from Dock. but I am unable to pinpoint the exact problem. Any assistance or insights into this issue would be greatly appreciated.

**Comment by sbryngelson** [comment]
Also having this problem, in my case witnessed for the `download_paper` extension. sioyek 2.0.0, python3.11, sioyek-python 0.31.11, MacOS Sonoma on an M1 Max. 

I can also add that if I launch Sioyek from a terminal, even without an argument, and then proceed to open files in that Sioyek session/window, the extension works as expected. It does not seem to recognize the extension at all if the Sioyek session/window was opened from VimTex or Sioyek.app via GUI.

**Comment by ahrm** [comment]
Does this solution help: https://github.com/ahrm/sioyek/issues/771#issuecomment-1715436107 ?

**Comment by ahrm** [comment]
> Is there a way to watch/log what sioyek is up to on MacOS when it wasn't opened from a terminal?

Unfortunately no.

**Comment by sbryngelson** [comment]
> @sbryngelson I believe I've identified the root of the problem. Could you please test with this `start_sioyek.sh` script?
> 
> ```shell
> #!/bin/bash
> 
> # This command simulates launching without any environment variables
> # env -i open -a /Applications/sioyek.app
> 
> # This command launches Sioyek normally with the current environment variables
> open -a /Applications/sioyek.app
> ```
> 
> Running env -i open doesn't work correctly, suggesting that the issue is related to environment variables not being set when launching Sioyek from the Dock. In contrast, the standard open command, which uses the current shell’s environment variables, works as expected.
> 
> If this also resolves the issue on your end, a potential solution would be to ensure that the necessary environment variables are set within the Sioyek application bundle for macOS, possibly through the [Info.plist](https://github.com/ahrm/sioyek/blob/main/resources/Info.plist?rgh-link-date=2023-11-02T09%3A11%3A01Z).

This is correct; the former does not work, and the latter does.
