### ISSUE TITLE
[feat] Text annotation improved

### ISSUE THREAD

**Issue by Dayan-Zhanchi** [ahrm/sioyek-python-extensions#23]
Thanks for creating Sioyek, really like what it has to offer!

I'm wondering if you have any plans on improving the text annotations in terms of it's capability? For instance, on Adobe Acrobat Reader you can create a comment (I think it's called sticky note) and write comments in a similiar fashion to how add_text does it in Sioyek. However, the one on Adobe is a bit better, since you can write really long paragraphs before getting cut-off and edit the text even after creating it. Also, there's a toggle on it, so that the comment bubble doesn't appear unless you hover over it or click on it, thus making it less cluttery. Here are some screenshots to show what I'm talking about. 1st is toggled off, 2nd is when you hover over it and 3rd is when you click on it. 

![sticky_comment](https://github.com/ahrm/sioyek-python-extensions/assets/16606436/b44c7599-192d-4d30-820e-377e06bd1f57)
![sticky_comment2](https://github.com/ahrm/sioyek-python-extensions/assets/16606436/3a3aa441-5832-4cce-b5c2-a6fcdcb5d47b)
![stick_comment1](https://github.com/ahrm/sioyek-python-extensions/assets/16606436/e921737f-1962-4670-8ef3-e62f36849dea)

Would be really nice if you could implement this, but I also understand that this is not a priority as it's more of a nice to have feature than a really important one.

In any case, thanks for your hard work and I look forward to seeing what more things you will add to Sioyek in the future!

**Comment by Dayan-Zhanchi** [comment]
Oh I'm dumb, seems like this can be done very easily as PyMuPDF has built-in support for this. Borrowing the code example from PyMuPDF [medium article](https://medium.com/@pymupdf/working-with-pdf-annotations-in-python-4d97e3788b7) (I assume it's theirs):

```py
import fitz


doc = fitz.open("input.pdf")  # open the input file
page = doc[0]  # load the desired page


point = fitz.Point(50, 50)  # top-left coordinates of the icon
annot = page.add_text_annot(point, "This is a sticky note.")


doc.save("input-annotated.pdf")  # save changes in a new file
doc.close()
```

So basically, instead of using page.add_freetext_annot(), one can instead use page.add_text_annot() to create such sticky note.

**Comment by Dayan-Zhanchi** [comment]
Just did some fast prototyping and seems that once the script adds the sticky note into a pdf file the user can't interact with it at all. Hovering over it displays nothing and clicking on does nothing, but when opening it on adobe acrobat reader it works as intended. I haven't dug around the code enough to know if this is just the way the base model of Sioyek injects new objects into the pdf in such a way that the original functionalities of these objects are completely lost? Is there no way to preserve the functionalities of the sticky note? Would appreciate it if I could get some pointers as to how to fix this.

Thanks in advance!

**Comment by ahrm** [comment]
We don't support PDF annotations in sioyek. The python scripts are for people who want to export their annotations to other pdf viewers. In the development branch of sioyek we do have freetext and visible bookmarks.

**Comment by Dayan-Zhanchi** [comment]
Alright I understand, I will just have to make do with the freetext then, that's the closest thing to sticky note, even though it's somewhat inferior to it. 

Anyways, thanks for a fast response!
